import { ProjectsSectionType } from '@/lib/types/sections';
import { getId } from '@/lib/utils/helper';

export const projectsSection: ProjectsSectionType = {
  title: 'my projects',
  projects: [
    {
      id: getId(),
      name: 'prompt App',
      url: 'https://prompt-app-seven.vercel.app/',
      repo: 'https://github.com/Tanwie12/prompt-app',
      img: '/promptApp.jpeg',
      year: 2023,
      tags: ['Nextjs', 'Tailwind'],
    },
    {
      id: getId(),
      name: 'Ecoomerce site (Mac)',
      url: 'https://eccomerce-client-ten.vercel.app/',
      repo: 'https://github.com/Tanwie12/Eccomerce_client',
      img: '/EcomClient.png',
      year: 2024,
      tags: ['Nextjs', 'tailwind'],
    },
    {
      id: getId(),
      name: 'Mac Dashboard',
      url: 'https://macecommerceplatform-hacking-priests-projects.vercel.app/',
      repo: 'https://github.com/Tanwie12/Ecommerce-Platform',
      img: '/Mac.jpeg',
      year: 2024,
      tags: ['Nextjs', 'tailwind','Nexui','shadcn'],
    },
    {
      id: getId(),
      name: 'PodCast app',
      url: 'https://podcastfinal.netlify.app',
      repo: 'https://github.com/Tanwie12/Podcast_App',
      img: '/podcast.jpeg',
      year: 2023,
      tags: ['Reactjs', 'css', 'tailwind'],
    },
    {
      id: getId(),
      name: 'Manage landind page',
      url: 'https://image-animations.vercel.app/',
      repo: 'https://github.com/Tanwie12/tailwindtest',
      img: 'https://app.netlify.com/.netlify/images?url=https://d33wubrfki0l68.cloudfront.net/655f6614ac9c920008334f5f/screenshot_2023-11-23-14-47-57-0000.png&fit=cover&h=500&q=40&w=800',
      year: 2022,
      tags: ['js', 'tailwind','html'],
    },
   
    {
      id: getId(),
      name: 'react table',
      url: 'https://react-test-six-gold.vercel.app/',
      repo: 'https://github.com/Tanwie12/react_test',
      img: '/reactTest.png',
      year: 2023,
      tags: ['Reactjs', 'NextUi','tailwind'],
    },
    // {
    //   id: getId(),
    //   name: 'rock paper scissors',
    //   url: 'https://rock-paper-scissors-kv.netlify.app/',
    //   repo: 'https://github.com/vatsalsinghkv/rock-paper-scissors',
    //   img: 'https://user-images.githubusercontent.com/68834718/162578706-b9e57735-6fbc-4c7b-8243-2a6ba447404e.jpg',
    //   year: 2022,
    //   tags: ['React', 'Sass'],
    // },
    // {
    //   id: getId(),
    //   name: 'todo app',
    //   url: 'https://todo-kv.netlify.app/',
    //   repo: 'https://github.com/vatsalsinghkv/todo-app',
    //   img: 'https://user-images.githubusercontent.com/68834718/152794002-0e7bc583-084b-4c39-83bb-d82d5dd642b2.png',
    //   year: 2022,
    //   tags: ['React', 'Sass', 'JS'],
    // },
    // {
    //   id: getId(),
    //   name: 'weather app',
    //   url: 'https://weather-kv.netlify.app/',
    //   repo: 'https://github.com/vatsalsinghkv/weather-app',
    //   img: 'https://user-images.githubusercontent.com/68834718/148419702-491fa08d-e520-4e2f-b219-374ec7118b2b.png',
    //   year: 2022,
    //   tags: ['Html', 'sass', 'JS', 'jQuery'],
    // },
    // {
    //   id: getId(),
    //   name: 'blogr landing page',
    //   url: 'https://blogr-kv.netlify.app/',
    //   repo: 'https://github.com/vatsalsinghkv/blogr-landing-page',
    //   img: 'https://user-images.githubusercontent.com/68834718/210222542-6455303d-c93e-430b-a5c8-96a431044184.png',
    //   year: 2021,
    //   tags: ['html', 'sass', 'JS'],
    // },
    // {
    //   id: getId(),
    //   name: 'natours',
    //   url: 'https://natours-kv.netlify.app/',
    //   repo: 'https://github.com/vatsalsinghkv/natours',
    //   img: 'https://user-images.githubusercontent.com/68834718/210223114-b4f64b44-2501-49c9-9fb7-b8e53fe654c6.png',
    //   year: 2021,
    //   tags: ['html', 'sass', 'JS'],
    // },
    // {
    //   id: getId(),
    //   name: 'nexter',
    //   url: 'https://vatsalsinghkv.github.io/nexter/',
    //   repo: 'https://github.com/vatsalsinghkv/nexter',
    //   img: 'https://user-images.githubusercontent.com/68834718/210224671-5501c5d9-a8d2-4044-a14c-38fb7e46a113.png',
    //   year: 2021,
    //   tags: ['html', 'sass'],
    // },
    // {
    //   id: getId(),
    //   name: 'IP address tracker',
    //   url: 'https://vatsalsinghkv.github.io/ip-address-tracker/',
    //   repo: 'https://github.com/vatsalsinghkv/ip-address-tracker',
    //   img: 'https://user-images.githubusercontent.com/68834718/210223386-03bcaa20-e649-4b3d-8709-59e42c6d685a.png',
    //   year: 2021,
    //   tags: ['html', 'bootstrap', 'JS'],
    // },
    // {
    //   id: getId(),
    //   name: 'calculator app',
    //   url: 'https://vatsalsinghkv.github.io/calculator-app/',
    //   repo: 'https://github.com/vatsalsinghkv/calculator-app/',
    //   img: 'https://user-images.githubusercontent.com/68834718/210223825-3b68d696-39c6-490c-9433-f315b7efccbd.png',
    //   year: 2021,
    //   tags: ['html', 'CSS', 'JS'],
    // },
    // {
    //   id: getId(),
    //   name: 'pig game',
    //   url: 'https://vatsalsinghkv.github.io/pig-game/',
    //   repo: 'https://github.com/vatsalsinghkv/pig-game',
    //   img: 'https://user-images.githubusercontent.com/68834718/210223527-de7fde7a-244e-4db5-8e33-d561afad6084.png',
    //   year: 2021,
    //   tags: ['html', 'CSS', 'JS'],
    // },
    // {
    //   id: getId(),
    //   name: 'bankist marketing',
    //   url: 'https://vatsalsinghkv.github.io/bankist-marketing/',
    //   repo: 'https://github.com/vatsalsinghkv/bankist-marketing',
    //   img: 'https://user-images.githubusercontent.com/68834718/210225545-989f79c3-cf05-4c53-b48e-b21f373b3734.png',
    //   year: 2021,
    //   tags: ['html', 'CSS', 'JS'],
    // },
  ],
};
