import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import Cursor from "@/components/ui/Cursor";
import ThemeProvider from "@/lib/hooks/use-theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
        <NextUIProvider>
        <Cursor className="hidden dark:lg:block" />
        {children}
        </NextUIProvider>
        </ThemeProvider>
        </body>
    </html>
  );
}
